require "lazy-config"
require "settings"
require "bufferline-config"
require "lualine-config"
require "nvim-tree-config"
require "telescope-config"
require "luasnip-config"
require "treesitter-config"
require "ft-override-config"
 -- require "ale-config"

